name: groupsharing
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.6.1

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  firebase_database: ^10.5.7

  # Core Flutter packages
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+18
  
  # Location and mapping
  geolocator: ^11.0.0
  latlong2: ^0.9.0
  google_maps_flutter: ^2.5.0
  
  # Image handling
  image_picker: ^1.0.7
  cached_network_image: ^3.3.1
  
  # OpenStreetMap integration
  flutter_map: ^6.1.0
  flutter_map_cancellable_tile_provider: ^2.0.0
  flutter_map_animations: ^0.6.0
  
  # Device sensors
  sensors_plus: ^4.0.2
  
  # URL handling
  share_plus: ^10.0.0
  url_launcher: ^6.2.5
  
  # Geocoding for reverse geocoding (coordinates to address)
  geocoding: ^2.1.1
  
  # Firebase packages for backend and real-time updates
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.3
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  connectivity_plus: ^5.0.2
  geofence_service: ^6.0.0+1
  app_links: ^6.2.0
  google_sign_in: ^6.1.6
  firebase_messaging: ^14.7.10
  cloud_functions: ^4.6.13

  # Device ringer mode (Android only)
  
  # State management
  provider: ^6.1.1
  
  # Notifications
  flutter_local_notifications: ^17.0.0
  
  # Permissions
  permission_handler: ^11.3.1
  app_settings: ^5.1.1
  
  # Utility packages
  uuid: ^4.2.2
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  # UI packages
  google_fonts: ^6.1.0
  flutter_slidable: ^3.0.1
  timeline_tile: ^2.0.0
  smooth_page_indicator: ^1.0.0+2
  path_provider: ^2.1.2
  battery_plus: ^5.0.0
  device_info_plus: ^9.0.0
  
  # Missing dependencies
  flutter_cache_manager: ^3.3.1
  firebase_crashlytics: ^3.4.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4 # Added mockito for mocking classes
  build_runner: ^2.4.8 # Added build_runner for code generation
  flutter_launcher_icons: ^0.13.1 # For generating launcher icons

dependency_overrides:
  # Fix Firebase web compatibility issues
  firebase_auth_web: 5.8.12
  firebase_core_web: 2.10.0
  firebase_storage_web: 3.6.21

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

  # The following section is specific to Flutter.
flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# Flutter Launcher Icons configuration
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/applogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  windows:
    generate: true
    image_path: "assets/images/applogo.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/applogo.png"
