// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'config/api_keys.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: ApiKeys.firebaseApiKeyWeb,
    appId: ApiKeys.webAppId,
    messagingSenderId: ApiKeys.messagingSenderId,
    projectId: ApiKeys.projectId,
    authDomain: ApiKeys.authDomain,
    storageBucket: ApiKeys.storageBucket,
    measurementId: 'G-ABCDEFGHIJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: ApiKeys.firebaseApiKeyAndroid,
    appId: ApiKeys.androidAppId,
    messagingSenderId: ApiKeys.messagingSenderId,
    projectId: ApiKeys.projectId,
    storageBucket: ApiKeys.storageBucket,
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: ApiKeys.firebaseApiKeyIOS,
    appId: ApiKeys.iosAppId,
    messagingSenderId: ApiKeys.messagingSenderId,
    projectId: ApiKeys.projectId,
    storageBucket: ApiKeys.storageBucket,
    iosBundleId: ApiKeys.iosBundleId,
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: ApiKeys.firebaseApiKeyIOS,
    appId: ApiKeys.iosAppId,
    messagingSenderId: ApiKeys.messagingSenderId,
    projectId: ApiKeys.projectId,
    storageBucket: ApiKeys.storageBucket,
    iosBundleId: ApiKeys.iosBundleId,
  );
}